export const siteConfig = Object.freeze({
  name: "Canny Next | Empowering Businesses Through Innovative Tech Solutions",
  description:
    "Welcome to Canny Next, the nexus of digital transformation where visionary technology converges with creative design. Our mission is to revolutionize businesses by offering a comprehensive suite of cutting-edge solutions. With expertise spanning ecommerce, Software as a Service (SaaS), and strategic consulting, we craft digital experiences that not only meet but exceed expectations.",
  url: "https://www.cannynext.com",
  ogImage: "https://www.cannynext.com/canny_next.jpeg",
  keywords: [
    "innovative ecommerce solutions",
    "cutting-edge SaaS platforms",
    "strategic tech consulting",
    "digital transformation services",
    "captivating web design",
    "user-centric online experiences",
    "technology-driven business growth",
    "tech services excellence",
    "cutting-edge ecommerce solutions",
    "revolutionary SaaS platforms",
    "strategic tech consulting services",
    "custom digital transformation",
    "stunning web design",
    "user-centric online experiences",
    "next-gen technology growth",
    "tech services innovation",
    "digital solutions excellence",
  ],
  icons: {
    icon: "/canny_next.svg",
    shortcut: "/canny_next.svg",
    apple: "/canny_next.svg",
  },
  links: {
    linkedIn: "https://in.linkedin.com/company/canny-next",
    twitter: "https://in.twitter.com/canny-next",
  },
  manifest: "/manifest/manifest.webmanifest",
});
